#!/usr/bin/env bash
# Rebuild data/questions.js from the PDFs in past_papers/.
#
# Needs: pdftotext (poppler) and perl. On Windows, Git Bash ships both.
#   bash tools/rebuild.sh
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
root="$(dirname "$here")"
work="$root/.build"
txt="$work/txt"

if [ ! -d "$root/past_papers" ]; then
  echo "past_papers/ is missing. It is gitignored, so put the PDFs back first." >&2
  exit 1
fi

mkdir -p "$txt"
echo "1/4  extracting text"
find "$root/past_papers" -name '*.pdf' | while read -r f; do
  rel="${f#"$root/"}"
  out="$txt/$(echo "$rel" | tr '/ ' '__' | sed 's/\.pdf$//').txt"
  pdftotext -layout -enc UTF-8 "$f" "$out" 2>/dev/null || echo "  skipped $rel"
done

echo "2/4  parsing multiple choice papers"
p1=(
  past_papers_2014_NIS_2014_paper1
  past_papers_2016_NIS_2016_paper_1
  past_papers_2018_NIS_2018_paper1
  past_papers_2021_NIS_G12_CHE_01_7RP
  "past_papers_2023_2023_NIS_G12_CHE_01_2RP_AFP_(1)"
  past_papers_2024_2024_NIS_G12_CHE_01_2RP_AFP
  past_papers_2025_2025_NIS_G12_CHE_01_2RP_AFP
)
for s in "${p1[@]}"; do
  [ -f "$txt/$s.txt" ] || { echo "  missing $s"; continue; }
  perl "$here/extract_p1.pl" "$txt/$s.txt" > "$work/out_$s.json"
  printf '  %-52s %s\n' "$s" "$(grep -c '"n":' "$work/out_$s.json") questions"
done

echo "3/4  reading mark schemes and structured papers"
for s in 2021_NIS_G12_CHE_01_MS_3RP 2024_2024_NIS_G12_CHE_01_MS_2RP 2025_2025_NIS_G12_CHE_01_MS_2RP; do
  [ -f "$txt/past_papers_$s.txt" ] || continue
  perl "$here/extract_ms1.pl" "$txt/past_papers_$s.txt" > "$work/key_$s.json"
done

p23=(
  2014_NIS_2014_paper2
  2016_NIS_2016_paper2
  2018_NIS_2018_paper2
  2021_NIS_G12_CHE_02_7RP
  "2022_2022_NIS_G12_CHE_02_2RP_AFP_(2)"
  2023_2023_NIS_G12_CHE_02_RP_AFP
  2024_2024_NIS_G12_CHE_02_2RP_AFP
  2025_2025_NIS_G12_CHE_02_2RP_AFP
  "2022_2022_NIS_G12_CHE_03_2RP_AFP_(3)"
  "2023_NIS_G12_CHE_03_7RP_AFP_(1)_(1)"
  2024_2024_NIS_G12_CHE_03_2RP_AFP
  "2025_2025_NIS_G12_CHE_03_2RP_AFP_(1)"
)
for s in "${p23[@]}"; do
  [ -f "$txt/past_papers_$s.txt" ] || { echo "  missing $s"; continue; }
  perl "$here/extract_p23.pl" "$txt/past_papers_$s.txt" > "$work/s_past_papers_$s.json"
done

echo "3b/4 reading the .docx mark schemes"
docx_pairs=(
  "2022|2|past_papers/2022/2022_NIS_G12_CHE_02_MS_2RP (1).docx"
  "2022|3|past_papers/2022/2022_NIS_G12_CHE_03_MS_2RP (2).docx"
  "2023|2|past_papers/2023/2023_NIS_G12_CHE_02_MS_2RP_AFP Explanation.docx"
)
for pair in "${docx_pairs[@]}"; do
  year="${pair%%|*}"; rest="${pair#*|}"; paper="${rest%%|*}"; rel="${rest#*|}"
  [ -f "$root/$rel" ] || { echo "  missing $rel"; continue; }
  tmp="$work/docx/${year}_p${paper}"
  rm -rf "$tmp"; mkdir -p "$tmp"
  unzip -o -q "$root/$rel" word/document.xml -d "$tmp" || continue
  perl "$here/extract_msdocx.pl" "$tmp/word/document.xml" > "$work/msdocx_${year}_p${paper}.json"
done

echo "3c/4 reading the examiner report booklets"
ook_pairs=(
  "2021|2|past_papers_OOK_ООК_2021_12_Химия_(анг)_РЕД"
  "2023|2|past_papers_OOK_ООК_G12_Химия_2_ком_2023"
  "2023|3|past_papers_OOK_ООК_G12_Химия_3_ком_2023"
  "2024|3|past_papers_OOK_ООК_2024_G12_Химия_3_компонент"
  "2025|2|past_papers_OOK_ООК_12CHEM_2_компонент_2025"
  "2025|3|past_papers_OOK_ООК_12CHEM_3_компонент_2025"
)
for pair in "${ook_pairs[@]}"; do
  year="${pair%%|*}"; rest="${pair#*|}"; paper="${rest%%|*}"; stem="${rest#*|}"
  [ -f "$txt/$stem.txt" ] || { echo "  missing $stem"; continue; }
  perl "$here/extract_ook.pl" "$txt/$stem.txt" > "$work/ook_${year}_p${paper}.json"
done

echo "4/4  building data/questions.js"
{
  printf 'window.CHEMPREP_QUESTIONS = '
  CHEMPREP_WORK="$work" perl "$here/build.pl"
  printf ';\n'
} > "$root/data/questions.js"

n=$(grep -o '"id":' "$root/data/questions.js" | wc -l)
echo "done: $n questions in data/questions.js"

echo "5/6  extracting and ranking the syllabus objectives"
for g in 11 12; do
  src="$root/goals/${g}th_grade_goals.pdf"
  [ -f "$src" ] || { echo "  missing ${g}th_grade_goals.pdf"; continue; }
  pdftotext -layout -enc UTF-8 "$src" "$txt/goals_g$g.txt" 2>/dev/null
  perl "$here/extract_goals.pl" "$txt/goals_g$g.txt" > "$work/obj_g$g.json"
done
if [ -f "$work/obj_g11.json" ] && [ -f "$work/obj_g12.json" ]; then
  perl -0pe 's/\]\s*\[/,\n/s' "$work/obj_g11.json" "$work/obj_g12.json" > "$work/obj_all.json"
  {
    printf 'window.CHEMPREP_OBJECTIVES = '
    perl "$here/rank_goals.pl" "$work/obj_all.json" "$root/data/questions.js"
    printf ';\n'
  } > "$root/data/objectives.js"
  echo "  $(grep -o '"code":' "$root/data/objectives.js" | wc -l) objectives ranked by archive coverage"
fi

echo "6/6  bundling the written practice bank"
{
  printf '/* Generated by tools/rebuild.sh from practice/*.js. Do not edit. */\n'
  printf 'window.CHEMPREP_PRACTICE = [];\n'
  printf '// same array, so the per-unit files below can just push onto it\n'
  printf 'var CHEMPREP_PRACTICE = window.CHEMPREP_PRACTICE;\n'
  for f in "$root"/practice/*.js; do
    [ -f "$f" ] || continue
    printf '\n/* --- %s --- */\n' "$(basename "$f")"
    cat "$f"
  done
} > "$root/data/practice.js"
p=$(grep -o "id: 'p-" "$root/data/practice.js" | wc -l)
echo "  $p written practice questions bundled"
